"""Group B catalog, Group C rings, suppliers core

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-01 22:59:35.431896

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ring_size_standards',
    sa.Column('from_standard', sa.String(length=10), nullable=False),
    sa.Column('from_label', sa.String(length=20), nullable=False),
    sa.Column('to_standard', sa.String(length=10), nullable=False),
    sa.Column('to_label', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_standard', 'from_label', 'to_standard')
    )
    op.create_table('categories',
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug')
    )
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_tenant_id'), 'media_assets', ['tenant_id'], unique=False)
    op.create_table('option_groups',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ui_type', sa.String(length=20), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_index(op.f('ix_option_groups_tenant_id'), 'option_groups', ['tenant_id'], unique=False)
    op.create_table('ring_sizes',
    sa.Column('standard', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('diameter_mm', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('circumference_mm', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'standard', 'label')
    )
    op.create_index(op.f('ix_ring_sizes_tenant_id'), 'ring_sizes', ['tenant_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('markup_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_tenant_id'), 'suppliers', ['tenant_id'], unique=False)
    op.create_table('factories',
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('min_order', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('handles_hallmarking', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factories_tenant_id'), 'factories', ['tenant_id'], unique=False)
    op.create_table('options',
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['option_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_group_id', 'code')
    )
    op.create_index(op.f('ix_options_option_group_id'), 'options', ['option_group_id'], unique=False)
    op.create_table('product_templates',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_supplier_id', sa.UUID(), nullable=True),
    sa.Column('is_bespoke_base', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code')
    )
    op.create_index(op.f('ix_product_templates_tenant_id'), 'product_templates', ['tenant_id'], unique=False)
    op.create_table('option_media_map',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_media_map_template_id'), 'option_media_map', ['template_id'], unique=False)
    op.create_table('ring_profiles',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('band_width_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('band_profile', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ring_profiles_template_id'), 'ring_profiles', ['template_id'], unique=False)
    op.create_table('template_components',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cad_volume_mm3', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('metal_assignable', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_components_template_id'), 'template_components', ['template_id'], unique=False)
    op.create_table('template_media',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_media_template_id'), 'template_media', ['template_id'], unique=False)
    op.create_table('template_option_groups',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('default_option_id', sa.UUID(), nullable=True),
    sa.Column('min_qty', sa.Integer(), nullable=True),
    sa.Column('max_qty', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_option_id'], ['options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['option_group_id'], ['option_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'option_group_id')
    )
    op.create_index(op.f('ix_template_option_groups_template_id'), 'template_option_groups', ['template_id'], unique=False)
    op.create_table('template_size_weight_factors',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('ring_size_id', sa.UUID(), nullable=False),
    sa.Column('weight_factor', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ring_size_id'], ['ring_sizes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'ring_size_id')
    )
    op.create_index(op.f('ix_template_size_weight_factors_template_id'), 'template_size_weight_factors', ['template_id'], unique=False)
    op.create_table('template_component_options',
    sa.Column('template_component_id', sa.UUID(), nullable=False),
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['option_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_component_id'], ['template_components.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_component_id', 'option_group_id')
    )
    op.create_index(op.f('ix_template_component_options_template_component_id'), 'template_component_options', ['template_component_id'], unique=False)
    op.create_table('template_manufacturability',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=True),
    sa.Column('min_band_thickness_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('min_wall_thickness_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('min_prong_thickness_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('prong_count', sa.Integer(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=True),
    sa.Column('stone_seat_tolerance_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('stone_measurement_min_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('stone_measurement_max_mm', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('requires_manual_cad_check', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['template_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_manufacturability_template_id'), 'template_manufacturability', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_manufacturability_template_id'), table_name='template_manufacturability')
    op.drop_table('template_manufacturability')
    op.drop_index(op.f('ix_template_component_options_template_component_id'), table_name='template_component_options')
    op.drop_table('template_component_options')
    op.drop_index(op.f('ix_template_size_weight_factors_template_id'), table_name='template_size_weight_factors')
    op.drop_table('template_size_weight_factors')
    op.drop_index(op.f('ix_template_option_groups_template_id'), table_name='template_option_groups')
    op.drop_table('template_option_groups')
    op.drop_index(op.f('ix_template_media_template_id'), table_name='template_media')
    op.drop_table('template_media')
    op.drop_index(op.f('ix_template_components_template_id'), table_name='template_components')
    op.drop_table('template_components')
    op.drop_index(op.f('ix_ring_profiles_template_id'), table_name='ring_profiles')
    op.drop_table('ring_profiles')
    op.drop_index(op.f('ix_option_media_map_template_id'), table_name='option_media_map')
    op.drop_table('option_media_map')
    op.drop_index(op.f('ix_product_templates_tenant_id'), table_name='product_templates')
    op.drop_table('product_templates')
    op.drop_index(op.f('ix_options_option_group_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_factories_tenant_id'), table_name='factories')
    op.drop_table('factories')
    op.drop_index(op.f('ix_suppliers_tenant_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_ring_sizes_tenant_id'), table_name='ring_sizes')
    op.drop_table('ring_sizes')
    op.drop_index(op.f('ix_option_groups_tenant_id'), table_name='option_groups')
    op.drop_table('option_groups')
    op.drop_index(op.f('ix_media_assets_tenant_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_table('ring_size_standards')
    # ### end Alembic commands ###
