"""Group D metals, Group E stones

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-01 23:02:35.525405

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metal_compatibility_rules',
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metal_compatibility_rules_tenant_id'), 'metal_compatibility_rules', ['tenant_id'], unique=False)
    op.create_table('metal_price_snapshots',
    sa.Column('metal', sa.String(length=30), nullable=False),
    sa.Column('karat', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_per_gram', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metal_price_snapshots_tenant_id'), 'metal_price_snapshots', ['tenant_id'], unique=False)
    op.create_table('metal_price_sources',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metal_price_sources_tenant_id'), 'metal_price_sources', ['tenant_id'], unique=False)
    op.create_table('metals',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_index(op.f('ix_metals_tenant_id'), 'metals', ['tenant_id'], unique=False)
    op.create_table('stone_shapes',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_index(op.f('ix_stone_shapes_tenant_id'), 'stone_shapes', ['tenant_id'], unique=False)
    op.create_table('stone_types',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_index(op.f('ix_stone_types_tenant_id'), 'stone_types', ['tenant_id'], unique=False)
    op.create_table('carat_price_bands',
    sa.Column('stone_type_id', sa.UUID(), nullable=False),
    sa.Column('carat_threshold', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['stone_type_id'], ['stone_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'stone_type_id', 'carat_threshold')
    )
    op.create_index(op.f('ix_carat_price_bands_tenant_id'), 'carat_price_bands', ['tenant_id'], unique=False)
    op.create_table('diamond_price_tables',
    sa.Column('stone_type_id', sa.UUID(), nullable=False),
    sa.Column('shape_id', sa.UUID(), nullable=False),
    sa.Column('carat_min', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('carat_max', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=False),
    sa.Column('clarity', sa.String(length=10), nullable=False),
    sa.Column('price_per_carat', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shape_id'], ['stone_shapes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stone_type_id'], ['stone_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diamond_price_tables_tenant_id'), 'diamond_price_tables', ['tenant_id'], unique=False)
    op.create_table('gemstone_price_tables',
    sa.Column('stone_type_id', sa.UUID(), nullable=False),
    sa.Column('shape_id', sa.UUID(), nullable=False),
    sa.Column('carat_min', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('carat_max', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('price_per_carat', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shape_id'], ['stone_shapes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stone_type_id'], ['stone_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemstone_price_tables_tenant_id'), 'gemstone_price_tables', ['tenant_id'], unique=False)
    op.create_table('metal_colors',
    sa.Column('metal_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_id', 'key')
    )
    op.create_index(op.f('ix_metal_colors_metal_id'), 'metal_colors', ['metal_id'], unique=False)
    op.create_table('metal_purities',
    sa.Column('metal_id', sa.UUID(), nullable=False),
    sa.Column('karat', sa.Integer(), nullable=True),
    sa.Column('fineness', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_id', 'fineness')
    )
    op.create_index(op.f('ix_metal_purities_metal_id'), 'metal_purities', ['metal_id'], unique=False)
    op.create_table('stone_quality_grades',
    sa.Column('stone_type_id', sa.UUID(), nullable=False),
    sa.Column('attribute', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stone_type_id'], ['stone_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stone_type_id', 'attribute', 'code')
    )
    op.create_index(op.f('ix_stone_quality_grades_stone_type_id'), 'stone_quality_grades', ['stone_type_id'], unique=False)
    op.create_table('supplier_stones',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('stone_type_id', sa.UUID(), nullable=False),
    sa.Column('shape_id', sa.UUID(), nullable=False),
    sa.Column('carat', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('color', sa.String(length=10), nullable=True),
    sa.Column('clarity', sa.String(length=10), nullable=True),
    sa.Column('cut', sa.String(length=20), nullable=True),
    sa.Column('polish', sa.String(length=20), nullable=True),
    sa.Column('symmetry', sa.String(length=20), nullable=True),
    sa.Column('fluorescence', sa.String(length=20), nullable=True),
    sa.Column('cert_lab', sa.String(length=20), nullable=True),
    sa.Column('cert_number', sa.String(length=50), nullable=True),
    sa.Column('cert_url', sa.String(length=1000), nullable=True),
    sa.Column('measurements', sa.String(length=100), nullable=True),
    sa.Column('ratio', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('depth_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('table_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=30), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('video_url', sa.String(length=1000), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['shape_id'], ['stone_shapes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stone_type_id'], ['stone_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'supplier_id', 'external_id')
    )
    op.create_index(op.f('ix_supplier_stones_tenant_id'), 'supplier_stones', ['tenant_id'], unique=False)
    op.create_table('metal_densities',
    sa.Column('metal_purity_id', sa.UUID(), nullable=False),
    sa.Column('metal_color_id', sa.UUID(), nullable=True),
    sa.Column('specific_gravity', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metal_color_id'], ['metal_colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metal_purity_id'], ['metal_purities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal_purity_id', 'metal_color_id')
    )
    op.create_index(op.f('ix_metal_densities_metal_purity_id'), 'metal_densities', ['metal_purity_id'], unique=False)
    op.create_table('stone_certificates',
    sa.Column('supplier_stone_id', sa.UUID(), nullable=False),
    sa.Column('lab', sa.String(length=20), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_stone_id'], ['supplier_stones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stone_certificates_supplier_stone_id'), 'stone_certificates', ['supplier_stone_id'], unique=False)
    op.create_table('material_options',
    sa.Column('metal_id', sa.UUID(), nullable=False),
    sa.Column('purity_id', sa.UUID(), nullable=False),
    sa.Column('color_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('fineness', sa.Integer(), nullable=False),
    sa.Column('density_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('recommended_for_engagement_rings', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['metal_colors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['density_id'], ['metal_densities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['metal_id'], ['metals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purity_id'], ['metal_purities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'metal_id', 'purity_id', 'color_id')
    )
    op.create_index(op.f('ix_material_options_tenant_id'), 'material_options', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_options_tenant_id'), table_name='material_options')
    op.drop_table('material_options')
    op.drop_index(op.f('ix_stone_certificates_supplier_stone_id'), table_name='stone_certificates')
    op.drop_table('stone_certificates')
    op.drop_index(op.f('ix_metal_densities_metal_purity_id'), table_name='metal_densities')
    op.drop_table('metal_densities')
    op.drop_index(op.f('ix_supplier_stones_tenant_id'), table_name='supplier_stones')
    op.drop_table('supplier_stones')
    op.drop_index(op.f('ix_stone_quality_grades_stone_type_id'), table_name='stone_quality_grades')
    op.drop_table('stone_quality_grades')
    op.drop_index(op.f('ix_metal_purities_metal_id'), table_name='metal_purities')
    op.drop_table('metal_purities')
    op.drop_index(op.f('ix_metal_colors_metal_id'), table_name='metal_colors')
    op.drop_table('metal_colors')
    op.drop_index(op.f('ix_gemstone_price_tables_tenant_id'), table_name='gemstone_price_tables')
    op.drop_table('gemstone_price_tables')
    op.drop_index(op.f('ix_diamond_price_tables_tenant_id'), table_name='diamond_price_tables')
    op.drop_table('diamond_price_tables')
    op.drop_index(op.f('ix_carat_price_bands_tenant_id'), table_name='carat_price_bands')
    op.drop_table('carat_price_bands')
    op.drop_index(op.f('ix_stone_types_tenant_id'), table_name='stone_types')
    op.drop_table('stone_types')
    op.drop_index(op.f('ix_stone_shapes_tenant_id'), table_name='stone_shapes')
    op.drop_table('stone_shapes')
    op.drop_index(op.f('ix_metals_tenant_id'), table_name='metals')
    op.drop_table('metals')
    op.drop_index(op.f('ix_metal_price_sources_tenant_id'), table_name='metal_price_sources')
    op.drop_table('metal_price_sources')
    op.drop_index(op.f('ix_metal_price_snapshots_tenant_id'), table_name='metal_price_snapshots')
    op.drop_table('metal_price_snapshots')
    op.drop_index(op.f('ix_metal_compatibility_rules_tenant_id'), table_name='metal_compatibility_rules')
    op.drop_table('metal_compatibility_rules')
    # ### end Alembic commands ###
