"""Group G rules, Group F CAD, Group H pricing

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-01 23:04:25.448255

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buffers',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buffers_tenant_id'), 'buffers', ['tenant_id'], unique=False)
    op.create_table('design_fees',
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_design_fees_tenant_id'), 'design_fees', ['tenant_id'], unique=False)
    op.create_table('engraving_costs',
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('base_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('per_char_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('makes_non_returnable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engraving_costs_tenant_id'), 'engraving_costs', ['tenant_id'], unique=False)
    op.create_table('fx_rates',
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('quote_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fx_rates_tenant_id'), 'fx_rates', ['tenant_id'], unique=False)
    op.create_table('price_calculations',
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('itemized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_calculations_config_hash'), 'price_calculations', ['config_hash'], unique=False)
    op.create_index(op.f('ix_price_calculations_tenant_id'), 'price_calculations', ['tenant_id'], unique=False)
    op.create_table('prototype_costs',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('base_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('credited_above_order_value_minor', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prototype_costs_tenant_id'), 'prototype_costs', ['tenant_id'], unique=False)
    op.create_table('setting_costs',
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.Column('per_stone_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_costs_tenant_id'), 'setting_costs', ['tenant_id'], unique=False)
    op.create_table('vat_rules',
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('price_includes_vat', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vat_rules_tenant_id'), 'vat_rules', ['tenant_id'], unique=False)
    op.create_table('labor_costs',
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_costs_tenant_id'), 'labor_costs', ['tenant_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('order_item_id', sa.UUID(), nullable=True),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('itemized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('metal_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fx_rate', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stone_price', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('margin_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vat_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('price_formula_version', sa.Integer(), nullable=False),
    sa.Column('rule_set_version', sa.Integer(), nullable=False),
    sa.Column('density_source_version', sa.Integer(), nullable=False),
    sa.Column('labor_cost_version', sa.Integer(), nullable=False),
    sa.Column('margin_rule_version', sa.Integer(), nullable=False),
    sa.Column('vat_rule_version', sa.Integer(), nullable=False),
    sa.Column('metal_price_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('fx_rate_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['fx_rate_snapshot_id'], ['fx_rates.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['metal_price_snapshot_id'], ['metal_price_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_tenant_id'), 'price_snapshots', ['tenant_id'], unique=False)
    op.create_table('render_jobs',
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_media_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['output_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_jobs_config_hash'), 'render_jobs', ['config_hash'], unique=False)
    op.create_index(op.f('ix_render_jobs_tenant_id'), 'render_jobs', ['tenant_id'], unique=False)
    op.create_table('future_3d_assets',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('glb_url', sa.String(length=1000), nullable=False),
    sa.Column('material_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mesh_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_future_3d_assets_template_id'), 'future_3d_assets', ['template_id'], unique=False)
    op.create_table('margins',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('band', sa.String(length=30), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_margins_tenant_id'), 'margins', ['tenant_id'], unique=False)
    op.create_table('price_formula',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_formula_tenant_id'), 'price_formula', ['tenant_id'], unique=False)
    op.create_table('rule_sets',
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'template_id', 'version')
    )
    op.create_index(op.f('ix_rule_sets_template_id'), 'rule_sets', ['template_id'], unique=False)
    op.create_index(op.f('ix_rule_sets_tenant_id'), 'rule_sets', ['tenant_id'], unique=False)
    op.create_table('cad_files',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('volume_mm3', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['template_components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cad_files_template_id'), 'cad_files', ['template_id'], unique=False)
    op.create_index(op.f('ix_cad_files_tenant_id'), 'cad_files', ['tenant_id'], unique=False)
    op.create_table('option_dependencies',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('when_option_id', sa.UUID(), nullable=False),
    sa.Column('requires_option_id', sa.UUID(), nullable=True),
    sa.Column('excludes_option_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['excludes_option_id'], ['options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_option_id'], ['options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['when_option_id'], ['options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_dependencies_rule_set_id'), 'option_dependencies', ['rule_set_id'], unique=False)
    op.create_table('rules',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_rule_set_id'), 'rules', ['rule_set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rules_rule_set_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_option_dependencies_rule_set_id'), table_name='option_dependencies')
    op.drop_table('option_dependencies')
    op.drop_index(op.f('ix_cad_files_tenant_id'), table_name='cad_files')
    op.drop_index(op.f('ix_cad_files_template_id'), table_name='cad_files')
    op.drop_table('cad_files')
    op.drop_index(op.f('ix_rule_sets_tenant_id'), table_name='rule_sets')
    op.drop_index(op.f('ix_rule_sets_template_id'), table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_price_formula_tenant_id'), table_name='price_formula')
    op.drop_table('price_formula')
    op.drop_index(op.f('ix_margins_tenant_id'), table_name='margins')
    op.drop_table('margins')
    op.drop_index(op.f('ix_future_3d_assets_template_id'), table_name='future_3d_assets')
    op.drop_table('future_3d_assets')
    op.drop_index(op.f('ix_render_jobs_tenant_id'), table_name='render_jobs')
    op.drop_index(op.f('ix_render_jobs_config_hash'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_price_snapshots_tenant_id'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_labor_costs_tenant_id'), table_name='labor_costs')
    op.drop_table('labor_costs')
    op.drop_index(op.f('ix_vat_rules_tenant_id'), table_name='vat_rules')
    op.drop_table('vat_rules')
    op.drop_index(op.f('ix_setting_costs_tenant_id'), table_name='setting_costs')
    op.drop_table('setting_costs')
    op.drop_index(op.f('ix_prototype_costs_tenant_id'), table_name='prototype_costs')
    op.drop_table('prototype_costs')
    op.drop_index(op.f('ix_price_calculations_tenant_id'), table_name='price_calculations')
    op.drop_index(op.f('ix_price_calculations_config_hash'), table_name='price_calculations')
    op.drop_table('price_calculations')
    op.drop_index(op.f('ix_fx_rates_tenant_id'), table_name='fx_rates')
    op.drop_table('fx_rates')
    op.drop_index(op.f('ix_engraving_costs_tenant_id'), table_name='engraving_costs')
    op.drop_table('engraving_costs')
    op.drop_index(op.f('ix_design_fees_tenant_id'), table_name='design_fees')
    op.drop_table('design_fees')
    op.drop_index(op.f('ix_buffers_tenant_id'), table_name='buffers')
    op.drop_table('buffers')
    # ### end Alembic commands ###
