"""Groups I-rest imports, J bespoke, K orders, L production, M customers

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-01 23:07:29.262240

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_subject_id'), 'consents', ['subject_id'], unique=False)
    op.create_index(op.f('ix_consents_tenant_id'), 'consents', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('addresses',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_addresses_customer_id'), 'addresses', ['customer_id'], unique=False)
    op.create_table('bespoke_requests',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('price_range_min_minor', sa.BigInteger(), nullable=True),
    sa.Column('price_range_max_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bespoke_requests_tenant_id'), 'bespoke_requests', ['tenant_id'], unique=False)
    op.create_table('carts',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carts_tenant_id'), 'carts', ['tenant_id'], unique=False)
    op.create_table('orders',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_tenant_id'), 'orders', ['tenant_id'], unique=False)
    op.create_table('supplier_import_jobs',
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_import_jobs_tenant_id'), 'supplier_import_jobs', ['tenant_id'], unique=False)
    op.create_table('supplier_price_lists',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('url_or_ref', sa.String(length=1000), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_price_lists_supplier_id'), 'supplier_price_lists', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_supplier_price_lists_tenant_id'), 'supplier_price_lists', ['tenant_id'], unique=False)
    op.create_table('bespoke_approvals',
    sa.Column('bespoke_request_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('becomes_order_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['becomes_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bespoke_approvals_bespoke_request_id'), 'bespoke_approvals', ['bespoke_request_id'], unique=False)
    op.create_table('bespoke_quotes',
    sa.Column('bespoke_request_id', sa.UUID(), nullable=False),
    sa.Column('itemized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bespoke_quotes_bespoke_request_id'), 'bespoke_quotes', ['bespoke_request_id'], unique=False)
    op.create_table('bespoke_revisions',
    sa.Column('bespoke_request_id', sa.UUID(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('cad_media_id', sa.UUID(), nullable=True),
    sa.Column('render_media_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cad_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['render_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bespoke_revisions_bespoke_request_id'), 'bespoke_revisions', ['bespoke_request_id'], unique=False)
    op.create_table('bespoke_uploads',
    sa.Column('bespoke_request_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bespoke_uploads_bespoke_request_id'), 'bespoke_uploads', ['bespoke_request_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_calculation_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_calculation_id'], ['price_calculations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_table('deposits',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('bespoke_request_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('credited_to_order_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['credited_to_order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_order_id'), 'deposits', ['order_id'], unique=False)
    op.create_table('factory_manufacturability',
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('can_cast', sa.Boolean(), nullable=False),
    sa.Column('can_set_stone', sa.Boolean(), nullable=False),
    sa.Column('can_engrave', sa.Boolean(), nullable=False),
    sa.Column('can_prototype', sa.Boolean(), nullable=False),
    sa.Column('supported_metals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('supported_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_stone_carat', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_manufacturability_factory_id'), 'factory_manufacturability', ['factory_id'], unique=False)
    op.create_index(op.f('ix_factory_manufacturability_tenant_id'), 'factory_manufacturability', ['tenant_id'], unique=False)
    op.create_table('factory_product_overrides',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=False),
    sa.Column('weight_override_g', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('cost_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factory_product_overrides_template_id'), 'factory_product_overrides', ['template_id'], unique=False)
    op.create_index(op.f('ix_factory_product_overrides_tenant_id'), 'factory_product_overrides', ['tenant_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('engraving_text', sa.String(length=100), nullable=True),
    sa.Column('ring_size_id', sa.UUID(), nullable=True),
    sa.Column('stone_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('non_returnable', sa.Boolean(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['price_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ring_size_id'], ['ring_sizes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('bespoke_request_id', sa.UUID(), nullable=True),
    sa.Column('psp', sa.String(length=20), nullable=False),
    sa.Column('psp_ref', sa.String(length=255), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_psp_ref'), 'payments', ['psp_ref'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('quotes',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('price_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['price_snapshots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_tenant_id'), 'quotes', ['tenant_id'], unique=False)
    op.create_table('shipments',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('carrier', sa.String(length=50), nullable=True),
    sa.Column('tracking', sa.String(length=255), nullable=True),
    sa.Column('insured', sa.Boolean(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipments_order_id'), 'shipments', ['order_id'], unique=False)
    op.create_table('supplier_import_rows',
    sa.Column('import_job_id', sa.UUID(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mapped', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['supplier_import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_import_rows_import_job_id'), 'supplier_import_rows', ['import_job_id'], unique=False)
    op.create_table('withdrawal_requests',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_medium', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_requests_order_id'), 'withdrawal_requests', ['order_id'], unique=False)
    op.create_index(op.f('ix_withdrawal_requests_tenant_id'), 'withdrawal_requests', ['tenant_id'], unique=False)
    op.create_table('bespoke_deposits',
    sa.Column('bespoke_request_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('non_refundable', sa.Boolean(), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bespoke_request_id'], ['bespoke_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bespoke_deposits_bespoke_request_id'), 'bespoke_deposits', ['bespoke_request_id'], unique=False)
    op.create_table('order_configurations',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('resolved_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_configurations_order_item_id'), 'order_configurations', ['order_item_id'], unique=False)
    op.create_table('production_jobs',
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('factory_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('spec_sheet_media_id', sa.UUID(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['factory_id'], ['factories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_sheet_media_id'], ['media_assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_jobs_order_item_id'), 'production_jobs', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_production_jobs_status'), 'production_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_production_jobs_tenant_id'), 'production_jobs', ['tenant_id'], unique=False)
    op.create_table('refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_table('hallmark_records',
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('metal', sa.String(length=30), nullable=True),
    sa.Column('fineness', sa.Integer(), nullable=True),
    sa.Column('responsibility_mark', sa.String(length=100), nullable=True),
    sa.Column('assay_office', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hallmark_records_production_job_id'), 'hallmark_records', ['production_job_id'], unique=False)
    op.create_table('production_files',
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_files_production_job_id'), 'production_files', ['production_job_id'], unique=False)
    op.create_table('production_notes',
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=4000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_notes_production_job_id'), 'production_notes', ['production_job_id'], unique=False)
    op.create_table('production_steps',
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_steps_production_job_id'), 'production_steps', ['production_job_id'], unique=False)
    op.create_index(op.f('ix_production_steps_status'), 'production_steps', ['status'], unique=False)
    op.create_table('qc_checks',
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('checklist', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('checked_by', sa.String(length=255), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_checks_production_job_id'), 'qc_checks', ['production_job_id'], unique=False)
    op.create_table('qc_photos',
    sa.Column('production_job_id', sa.UUID(), nullable=False),
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['production_job_id'], ['production_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qc_photos_production_job_id'), 'qc_photos', ['production_job_id'], unique=False)
    op.create_foreign_key(None, 'price_snapshots', 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(None, 'price_snapshots', 'quotes', ['quote_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'price_snapshots', type_='foreignkey')
    op.drop_constraint(None, 'price_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_qc_photos_production_job_id'), table_name='qc_photos')
    op.drop_table('qc_photos')
    op.drop_index(op.f('ix_qc_checks_production_job_id'), table_name='qc_checks')
    op.drop_table('qc_checks')
    op.drop_index(op.f('ix_production_steps_status'), table_name='production_steps')
    op.drop_index(op.f('ix_production_steps_production_job_id'), table_name='production_steps')
    op.drop_table('production_steps')
    op.drop_index(op.f('ix_production_notes_production_job_id'), table_name='production_notes')
    op.drop_table('production_notes')
    op.drop_index(op.f('ix_production_files_production_job_id'), table_name='production_files')
    op.drop_table('production_files')
    op.drop_index(op.f('ix_hallmark_records_production_job_id'), table_name='hallmark_records')
    op.drop_table('hallmark_records')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_production_jobs_tenant_id'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_status'), table_name='production_jobs')
    op.drop_index(op.f('ix_production_jobs_order_item_id'), table_name='production_jobs')
    op.drop_table('production_jobs')
    op.drop_index(op.f('ix_order_configurations_order_item_id'), table_name='order_configurations')
    op.drop_table('order_configurations')
    op.drop_index(op.f('ix_bespoke_deposits_bespoke_request_id'), table_name='bespoke_deposits')
    op.drop_table('bespoke_deposits')
    op.drop_index(op.f('ix_withdrawal_requests_tenant_id'), table_name='withdrawal_requests')
    op.drop_index(op.f('ix_withdrawal_requests_order_id'), table_name='withdrawal_requests')
    op.drop_table('withdrawal_requests')
    op.drop_index(op.f('ix_supplier_import_rows_import_job_id'), table_name='supplier_import_rows')
    op.drop_table('supplier_import_rows')
    op.drop_index(op.f('ix_shipments_order_id'), table_name='shipments')
    op.drop_table('shipments')
    op.drop_index(op.f('ix_quotes_tenant_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_psp_ref'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_factory_product_overrides_tenant_id'), table_name='factory_product_overrides')
    op.drop_index(op.f('ix_factory_product_overrides_template_id'), table_name='factory_product_overrides')
    op.drop_table('factory_product_overrides')
    op.drop_index(op.f('ix_factory_manufacturability_tenant_id'), table_name='factory_manufacturability')
    op.drop_index(op.f('ix_factory_manufacturability_factory_id'), table_name='factory_manufacturability')
    op.drop_table('factory_manufacturability')
    op.drop_index(op.f('ix_deposits_order_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_bespoke_uploads_bespoke_request_id'), table_name='bespoke_uploads')
    op.drop_table('bespoke_uploads')
    op.drop_index(op.f('ix_bespoke_revisions_bespoke_request_id'), table_name='bespoke_revisions')
    op.drop_table('bespoke_revisions')
    op.drop_index(op.f('ix_bespoke_quotes_bespoke_request_id'), table_name='bespoke_quotes')
    op.drop_table('bespoke_quotes')
    op.drop_index(op.f('ix_bespoke_approvals_bespoke_request_id'), table_name='bespoke_approvals')
    op.drop_table('bespoke_approvals')
    op.drop_index(op.f('ix_supplier_price_lists_tenant_id'), table_name='supplier_price_lists')
    op.drop_index(op.f('ix_supplier_price_lists_supplier_id'), table_name='supplier_price_lists')
    op.drop_table('supplier_price_lists')
    op.drop_index(op.f('ix_supplier_import_jobs_tenant_id'), table_name='supplier_import_jobs')
    op.drop_table('supplier_import_jobs')
    op.drop_index(op.f('ix_orders_tenant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_carts_tenant_id'), table_name='carts')
    op.drop_table('carts')
    op.drop_index(op.f('ix_bespoke_requests_tenant_id'), table_name='bespoke_requests')
    op.drop_table('bespoke_requests')
    op.drop_index(op.f('ix_addresses_customer_id'), table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_consents_tenant_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_subject_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
