"""Group N SEO/GEO, Group O merchant feeds, Group P system

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-01 23:09:13.896686

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_blocks',
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('concise_answer', sa.String(length=2000), nullable=False),
    sa.Column('supporting', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_blocks_tenant_id'), 'answer_blocks', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('content_blocks',
    sa.Column('ref_type', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('body', sa.String(length=20000), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_blocks_tenant_id'), 'content_blocks', ['tenant_id'], unique=False)
    op.create_table('faq_blocks',
    sa.Column('ref_type', sa.String(length=30), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=5000), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_blocks_tenant_id'), 'faq_blocks', ['tenant_id'], unique=False)
    op.create_table('hreflang_groups',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_index(op.f('ix_hreflang_groups_tenant_id'), 'hreflang_groups', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_table('merchant_feed_rules',
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_feed_rules_tenant_id'), 'merchant_feed_rules', ['tenant_id'], unique=False)
    op.create_table('merchant_feeds',
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'channel', 'market', 'locale', 'currency')
    )
    op.create_index(op.f('ix_merchant_feeds_tenant_id'), 'merchant_feeds', ['tenant_id'], unique=False)
    op.create_table('price_refresh_log',
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('metal_or_pair', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_refresh_log_tenant_id'), 'price_refresh_log', ['tenant_id'], unique=False)
    op.create_table('seo_indexing_rules',
    sa.Column('pattern', sa.String(length=500), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_indexing_rules_tenant_id'), 'seo_indexing_rules', ['tenant_id'], unique=False)
    op.create_table('seo_internal_links',
    sa.Column('from_ref', sa.String(length=255), nullable=False),
    sa.Column('to_ref', sa.String(length=255), nullable=False),
    sa.Column('anchor', sa.String(length=255), nullable=True),
    sa.Column('context', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_internal_links_tenant_id'), 'seo_internal_links', ['tenant_id'], unique=False)
    op.create_table('seo_pages',
    sa.Column('page_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('follow', sa.Boolean(), nullable=False),
    sa.Column('schema_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug', 'locale', 'market')
    )
    op.create_index(op.f('ix_seo_pages_tenant_id'), 'seo_pages', ['tenant_id'], unique=False)
    op.create_table('seo_redirects',
    sa.Column('from_path', sa.String(length=1000), nullable=False),
    sa.Column('to_path', sa.String(length=1000), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'from_path')
    )
    op.create_index(op.f('ix_seo_redirects_tenant_id'), 'seo_redirects', ['tenant_id'], unique=False)
    op.create_table('sitemaps',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitemaps_tenant_id'), 'sitemaps', ['tenant_id'], unique=False)
    op.create_table('topic_clusters',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pillar_ref', sa.String(length=255), nullable=True),
    sa.Column('members', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_clusters_tenant_id'), 'topic_clusters', ['tenant_id'], unique=False)
    op.create_table('hreflang_urls',
    sa.Column('hreflang_group_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hreflang_group_id'], ['hreflang_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hreflang_urls_hreflang_group_id'), 'hreflang_urls', ['hreflang_group_id'], unique=False)
    op.create_table('image_metadata',
    sa.Column('media_asset_id', sa.UUID(), nullable=False),
    sa.Column('alt', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_metadata_media_asset_id'), 'image_metadata', ['media_asset_id'], unique=False)
    op.create_table('merchant_category_mappings',
    sa.Column('internal_category_id', sa.UUID(), nullable=False),
    sa.Column('google_product_category', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['internal_category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'internal_category_id')
    )
    op.create_index(op.f('ix_merchant_category_mappings_tenant_id'), 'merchant_category_mappings', ['tenant_id'], unique=False)
    op.create_table('merchant_feed_items',
    sa.Column('merchant_feed_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.String(length=100), nullable=False),
    sa.Column('item_group_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('image_link', sa.String(length=1000), nullable=True),
    sa.Column('additional_image_link', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=False),
    sa.Column('sale_price_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=20), nullable=False),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('brand', sa.String(length=70), nullable=True),
    sa.Column('gtin', sa.String(length=50), nullable=True),
    sa.Column('mpn', sa.String(length=70), nullable=True),
    sa.Column('identifier_exists', sa.Boolean(), nullable=False),
    sa.Column('google_product_category', sa.String(length=255), nullable=True),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('custom_label_0', sa.String(length=100), nullable=True),
    sa.Column('custom_label_1', sa.String(length=100), nullable=True),
    sa.Column('custom_label_2', sa.String(length=100), nullable=True),
    sa.Column('custom_label_3', sa.String(length=100), nullable=True),
    sa.Column('custom_label_4', sa.String(length=100), nullable=True),
    sa.Column('shipping_label', sa.String(length=100), nullable=True),
    sa.Column('return_policy_label', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_feed_id'], ['merchant_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_feed_id', 'offer_id')
    )
    op.create_index(op.f('ix_merchant_feed_items_merchant_feed_id'), 'merchant_feed_items', ['merchant_feed_id'], unique=False)
    op.create_table('seo_metadata',
    sa.Column('seo_page_id', sa.UUID(), nullable=False),
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('seo_description', sa.String(length=500), nullable=True),
    sa.Column('h1', sa.String(length=255), nullable=True),
    sa.Column('primary_keyword', sa.String(length=255), nullable=True),
    sa.Column('secondary_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_intent', sa.String(length=30), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seo_page_id'], ['seo_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_metadata_seo_page_id'), 'seo_metadata', ['seo_page_id'], unique=False)
    op.create_table('sitemap_items',
    sa.Column('sitemap_id', sa.UUID(), nullable=False),
    sa.Column('loc', sa.String(length=1000), nullable=False),
    sa.Column('lastmod', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changefreq', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=5), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sitemap_id'], ['sitemaps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sitemap_items_sitemap_id'), 'sitemap_items', ['sitemap_id'], unique=False)
    op.create_table('indexable_configurations',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('selections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('merchant_feed_enabled', sa.Boolean(), nullable=False),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('price_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['price_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['product_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku'),
    sa.UniqueConstraint('tenant_id', 'template_id', 'config_hash', 'market', 'locale')
    )
    op.create_index(op.f('ix_indexable_configurations_template_id'), 'indexable_configurations', ['template_id'], unique=False)
    op.create_index(op.f('ix_indexable_configurations_tenant_id'), 'indexable_configurations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indexable_configurations_tenant_id'), table_name='indexable_configurations')
    op.drop_index(op.f('ix_indexable_configurations_template_id'), table_name='indexable_configurations')
    op.drop_table('indexable_configurations')
    op.drop_index(op.f('ix_sitemap_items_sitemap_id'), table_name='sitemap_items')
    op.drop_table('sitemap_items')
    op.drop_index(op.f('ix_seo_metadata_seo_page_id'), table_name='seo_metadata')
    op.drop_table('seo_metadata')
    op.drop_index(op.f('ix_merchant_feed_items_merchant_feed_id'), table_name='merchant_feed_items')
    op.drop_table('merchant_feed_items')
    op.drop_index(op.f('ix_merchant_category_mappings_tenant_id'), table_name='merchant_category_mappings')
    op.drop_table('merchant_category_mappings')
    op.drop_index(op.f('ix_image_metadata_media_asset_id'), table_name='image_metadata')
    op.drop_table('image_metadata')
    op.drop_index(op.f('ix_hreflang_urls_hreflang_group_id'), table_name='hreflang_urls')
    op.drop_table('hreflang_urls')
    op.drop_index(op.f('ix_topic_clusters_tenant_id'), table_name='topic_clusters')
    op.drop_table('topic_clusters')
    op.drop_index(op.f('ix_sitemaps_tenant_id'), table_name='sitemaps')
    op.drop_table('sitemaps')
    op.drop_index(op.f('ix_seo_redirects_tenant_id'), table_name='seo_redirects')
    op.drop_table('seo_redirects')
    op.drop_index(op.f('ix_seo_pages_tenant_id'), table_name='seo_pages')
    op.drop_table('seo_pages')
    op.drop_index(op.f('ix_seo_internal_links_tenant_id'), table_name='seo_internal_links')
    op.drop_table('seo_internal_links')
    op.drop_index(op.f('ix_seo_indexing_rules_tenant_id'), table_name='seo_indexing_rules')
    op.drop_table('seo_indexing_rules')
    op.drop_index(op.f('ix_price_refresh_log_tenant_id'), table_name='price_refresh_log')
    op.drop_table('price_refresh_log')
    op.drop_index(op.f('ix_merchant_feeds_tenant_id'), table_name='merchant_feeds')
    op.drop_table('merchant_feeds')
    op.drop_index(op.f('ix_merchant_feed_rules_tenant_id'), table_name='merchant_feed_rules')
    op.drop_table('merchant_feed_rules')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_hreflang_groups_tenant_id'), table_name='hreflang_groups')
    op.drop_table('hreflang_groups')
    op.drop_index(op.f('ix_faq_blocks_tenant_id'), table_name='faq_blocks')
    op.drop_table('faq_blocks')
    op.drop_index(op.f('ix_content_blocks_tenant_id'), table_name='content_blocks')
    op.drop_table('content_blocks')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_answer_blocks_tenant_id'), table_name='answer_blocks')
    op.drop_table('answer_blocks')
    # ### end Alembic commands ###
